version: '3.1'

services:
  db:
    image: mariadb:10.1.34
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: Jugger
      MYSQL_USER: jugger
      MYSQL_PASSWORD: jugger