openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /users:
    get:
      tags:
        - User
      summary: Returns a list of users.
      operationId: getUsers
      responses:
        200:
          description: OK
    put:
      tags:
        - User
      summary: creats User
      operationId: createUser
      requestBody:
        content:
          application/json:
            schema:
              required: true
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          maxLength: 20
